name: Node.js CI

on:
    push:
        branches: [ main ]


jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        strategy:
            matrix:
                node-version: [20.x]

        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm install
        - run: npx semantic-release
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}